import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar structure.
 *
 * The "Guides" section used to be a single autogenerated flat list
 * of ~20 recipes, which is hard to skim. It's now grouped into
 * four semantic sub-categories (Rendering, Search, Data &
 * interaction, Accessibility) plus the Animations guide promoted to
 * the top of Guides because it's the newest and cross-cutting.
 *
 * URLs are unchanged — files still live in `docs/guides/*.md`, so
 * external links keep working. Only the in-sidebar presentation
 * differs.
 *
 * Each category has a `link: { type: 'generated-index' }` so the
 * header itself is clickable and opens an auto-built index page
 * listing every recipe in the category with its frontmatter
 * description. This gives the maintainer one stable URL per
 * category, and newcomers a "here's everything under X" landing
 * page.
 *
 * When adding a new guide:
 *   1. Create `docs/guides/<slug>.md` as usual.
 *   2. Add `'guides/<slug>'` to the right category below.
 *   3. Keep `sidebar_position` in the frontmatter for ordering
 *      within the category.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: ['intro', 'installation', 'quick-start', 'migration-from-upstream'],
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      collapsed: false,
      items: [
        'components/dropdown',
        'components/multi-select',
        'components/select-country',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Recipes',
        description:
          'Task-oriented recipes for common customization, styling, and integration scenarios.',
        slug: '/guides',
      },
      items: [
        // Animations lifted to the top of Guides — it's cross-cutting
        // (applies to Dropdown, MultiSelect, chips, and rows alike)
        // and is the most recently added recipe.
        'guides/animations',

        {
          type: 'category',
          label: 'Rendering',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Rendering recipes',
            description:
              'Replace parts of the default layout — trigger body, list rows, icons, modal header, empty state, section headers — with custom JSX.',
            slug: '/guides/rendering',
          },
          items: [
            'guides/custom-trigger',
            'guides/icon-per-state',
            'guides/modal-header',
            'guides/empty-state',
            'guides/sectioned-lists',
            'guides/multi-select-inside-mode',
            'guides/nested-in-modal',
          ],
        },
        {
          type: 'category',
          label: 'Search',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Search recipes',
            description:
              'Tune the built-in search: match against different fields, write a custom matcher, forward TextInput props, or react to cleared search.',
            slug: '/guides/search',
          },
          items: [
            'guides/custom-search-field',
            'guides/custom-search-matcher',
            'guides/on-change-text',
            'guides/search-input-props',
            'guides/text-input-passthrough',
          ],
        },
        {
          type: 'category',
          label: 'Data & interaction',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Data & interaction recipes',
            description:
              'Control which items appear, how they order, when the list loads, and when it opens — disabled items, exclusion, pagination, imperative ref.',
            slug: '/guides/interaction',
          },
          items: [
            'guides/disabled-items',
            'guides/exclusion',
            'guides/selected-ordering',
            'guides/end-reached-pagination',
            'guides/imperative-open-close',
          ],
        },
        {
          type: 'category',
          label: 'Accessibility & text',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Accessibility & text recipes',
            description:
              'Enlarge tap targets, respect the system font scale, and other a11y / text knobs.',
            slug: '/guides/a11y',
          },
          items: ['guides/hit-slop', 'guides/font-scaling'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      collapsed: false,
      items: ['accessibility', 'why-this-fork'],
    },
  ],
};

export default sidebars;
