import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: ['intro', 'installation', 'quick-start', 'migration-from-upstream'],
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      collapsed: false,
      items: [
        'components/dropdown',
        'components/multi-select',
        'components/select-country',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      collapsed: false,
      items: ['accessibility', 'why-this-fork'],
    },
  ],
};

export default sidebars;
